### PR TITLE
mobile- contact -form

### PR DESCRIPTION
**Pull request by ademibowale**
new pull request for the mobile contact form project.

### CODE REVIEW

**Comment by ademibowale** [comment]
this is my new mobile contact form project .

**Review by BenMukebo — COMMENTED** [review]
## Status: Invalid ❌

### Hi @ademibowale,
Please fix the issue mentioned below and then request for code review

### Reason

- [ ] This is a pair programming project, I can see only one developer worked on this project. Please make sure that both of you push commit messages. The reviewer will check the commit history to make sure that everybody has contributed code to the project.

#### Please make sure to submit code review when you are done with the changes that was requested

**Don't worry you still have same number of requests left as previous.**


Cheers and Happy Coding :clap: :clap: :clap: 

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ademibowale** [comment]
@BenMukebo please  i need help on my project i have been battling with this for 3days now as you can see i run the stylelint on my vscode terminal and it pass shows no error but if i push it to github and make the pull request its given me stylelint error it says error in 222:14 and by check on that line 222 i cant see any error on my css code  line 222 and above.please help me out.
Screenshot (5)
Screenshot (6)

**Comment by BenMukebo** [comment]
Hello, @ademibowale 
Sorry for the late response. I see that the problem is not solved yet. Please make a zoom call. We will correct this error.
Don't worry, man.

**Comment by ademibowale** [comment]
Ok thank you so much I have created a new repo and copy my work

**Comment by ademibowale** [comment]
pls i am stuck with my project again on desk-top version i dont want to
repeat again by submitting so late like last week that couses my block
repetition
please can i send you zoom invite to help me out ?

**Comment by ademibowale** [comment]
this is my zoom invite
https://microverse.zoom.us/j/95301970626?pwd=UG84aVRXMnY3QjB4MkxhaUJXd29wZz09

**Pull request closed without merging**
